"""Build a throwaway harness for the Modpoll Console panel chrome.

The point is that the harness runs the *shipped* code rather than a copy of it:
the stylesheet, the pane/grip block and the expand block are lifted out of
Modpoll-Console.user.js on every build, so a change to the userscript cannot
quietly stop being the thing under test. Everything the panel would normally get
from the IWMAC page — w2ui, Plant Term, GM storage — is stubbed.

    python make-harness.py && python -m http.server 8791

Lives beside the script it tests; harness.html is generated and ignored.
"""

import io
import re
from pathlib import Path

SRC = Path(__file__).resolve().parents[1] / "Modpoll-Console.user.js"
OUT = Path(__file__).with_name("harness.html")

src = io.open(SRC, encoding="utf-8", newline="").read()
version = re.search(r"@version\s+(\S+)", src).group(1)


def between(start, end, after=0):
    a = src.index(start, after)
    b = src.index(end, a)
    return src[a:b].rstrip()


# The stylesheet, with the panel id interpolation resolved.
style = re.search(r"const STYLE = `(.*?)\n    `;", src, re.S).group(1)
style = style.replace("${PANEL_ID}", "mpc-panel")

# PANES / paneHeight / setPaneHeight / makeGrip.
pane_block = between("    const PANES = {", "\n    /*\n     * Four corner brackets")

# ICON_* / placeExpandButton / syncExpandButton / setExpanded / watchExpanded.
expand_block = between("    /*\n     * Four corner brackets", "    const MIRROR_LINE_CAP")

# setGridColumns, lifted too: the last heading's padding is part of what is
# being checked, so a hand-written copy here would be testing the wrong thing.
grid_columns = between("    function setGridColumns(columns) {", "\n    /*\n     * A register on its own")

# The column sets, the format table, the rounding helper, the delta bookkeeping
# and renderGrid itself — so what the grid puts in each cell is under test as
# shipped rather than as retyped here.
formats = between("    const FORMATS = [", "\n    const TOOLBOX_SQL_URL")
tables = between("    const REGISTER_TABLES = [", "\n    // Serial defaults per driver family")
# The detail view, so what a click on a row shows is under test as shipped.
detail = between("    function readingDetailSections(", "\n    function renderEmptyGrid(")
# log(), so whether the log follows its tail is tested as shipped.
logfn = between("    function log(text, level) {", "\n    /**\n     * Everything the shell printed")
# The progress strip: show, fill, hide.
progress = between("    let progressHideTimer = null;", "\n    function setDot(state) {")
# The point-list parser and everything it decodes with, so a list in a test is
# parsed by the real parser rather than hand-built.
pointlist = between("    const DATATYPE_EXCEPTIONS = {", "\n    /**\n     * Points become poll ranges")
# The real lookups from a reading to its list point and its plant parameters.
names = between("    /** What the plant itself calls this register", "\n    /**\n     * What one register is, in the order someone asks it")
# enrichValue, asRanges, impliedScale, describeForAI, exportResult, exportParts.
exporting = between("    function enrichValue(", "\n    /*\n     * Where does this device actually keep anything?")
stamp = between("    function nowStamp() {", "\n    // ------------------------------------------------- command model")
columns = between("    const REGISTER_COLUMNS = [", "\n    const POINT_COLUMNS = [")
watch = between("    // Printed reference -> the value seen on the previous poll",
                "\n    function log(text, level) {")
render_grid = between("    function renderGrid(result) {", "\n    async function runOnce() {")

# The doc comment that sits above EXPAND_RESERVE, kept for readability only.
OUT.write_text(f"""<!doctype html>
<meta charset="utf-8">
<title>Modpoll Console panel-chrome harness v{version}</title>
<!-- Generated by make-harness.py from Modpoll-Console.user.js v{version}. Do not edit. -->
<style>
body{{margin:0;font:12px Arial}}
#page-chrome{{height:60px;background:#dfe3e9;border-bottom:1px solid #c8ccd4;padding:8px}}
#host{{height:520px}}
{style}
</style>
<div id="page-chrome">stands in for IWMAC's own header and sidebar</div>
<div id="host"></div>
<script>
// ---- stubs for everything the IWMAC page would supply ---------------------
const store = {{}};
const storeGet = (k, d) => (k in store ? store[k] : d);
const storeSet = (k, v) => {{ store[k] = v; }};
const ui = {{}};
const VERSION = '{version}';
const plantIdFromHost = () => '2313';
// What the IWMAC page and the rest of the script would supply to renderGrid.
let pointList = null;
let plantNames = null;
let redrawGrid = null;
// State the rest of the script would hold.
let lastResult = null;
let lastVerification = null;
let lastScan = null;
let _unitsCache = null;
const REPORT_CHUNK_LIMIT = 30000;
const resultFilename = () => 'modpoll_test.json';
const aimAtRegister = () => '';
function el(tag, props, kids) {{
    const node = Object.assign(document.createElement(tag), props || {{}});
    for (const kid of kids || []) node.appendChild(kid);
    return node;
}}

// ---- lifted verbatim from Modpoll-Console.user.js ------------------------
{formats}

{tables}

{stamp}

{pointlist}

{names}

{exporting}

{logfn}

{progress}

{detail}

{columns}

{watch}

{pane_block}

{expand_block}

{grid_columns}

{render_grid}
// ---- end lifted code -----------------------------------------------------

function renderEmptyGrid(message) {{
    ui.gridBody.textContent = '';
    ui.gridBody.appendChild(el('tr', {{}}, [
        el('td', {{ className: 'mpc-empty', colSpan: (ui.gridColumns || REGISTER_COLUMNS).length, textContent: message }}),
    ]));
    placeExpandButton();
}}
function fillGrid(rowCount) {{
    ui.gridBody.textContent = '';
    const frag = document.createDocumentFragment();
    for (let i = 0; i < rowCount; i++) {{
        frag.appendChild(el('tr', {{}}, (ui.gridColumns || REGISTER_COLUMNS).map((c, n) =>
            el('td', {{ textContent: n === 2 ? 'Extract motor frequency output' : String(84 + i) }}))));
    }}
    ui.gridBody.appendChild(frag);
    placeExpandButton();
}}

const panel = el('div', {{ id: 'mpc-panel' }});
ui.dot = el('span', {{ className: 'mpc-dot', title: 'Idle' }});
const head = el('div', {{ className: 'mpc-head' }}, [
    el('span', {{ className: 'mpc-title', textContent: 'Modpoll' }}),
    el('span', {{ className: 'mpc-ver', textContent: 'v' + VERSION + ' \\u00b7 plant ' + plantIdFromHost() + ' \\u00b7 read only' }}),
    ui.dot,
]);
const body = ui.body = el('div', {{ className: 'mpc-body' }});
const form = el('div', {{ className: 'mpc-form' }});
body.appendChild(form);
form.appendChild(el('div', {{ style: 'grid-column:span 12;height:150px;background:#f4f6f9;border:1px dashed #c8ccd4', textContent: ' the form rows' }}));
ui.expand = el('button', {{ className: 'mpc-expand', type: 'button' }});
ui.expand.addEventListener('click', () => setExpanded(!isExpanded()));
// The progress strip, built the way buildPanel builds it.
ui.progressFill = el('div');
ui.progressText = el('span', {{ className: 'mpc-ptext' }});
ui.progress = el('div', {{ className: 'mpc-progress mpc-hidden' }}, [el('div', {{ className: 'mpc-bar' }}, [ui.progressFill]), ui.progressText]);
form.appendChild(ui.progress);
ui.filterZero = el('input', {{ type: 'checkbox', id: 'mpc-hidezero' }});
ui.filterZero.addEventListener('change', () => {{ if (redrawGrid) redrawGrid(); }});
form.appendChild(el('label', {{ className: 'mpc-check mpc-span3', htmlFor: 'mpc-hidezero' }},
    [ui.filterZero, el('span', {{ textContent: 'Hide zero values' }})]));
ui.gridBody = el('tbody');
ui.gridCols = el('colgroup');
ui.gridHead = el('thead');
const table = el('table', {{ className: 'mpc-grid' }}, [ui.gridCols, ui.gridHead, ui.gridBody]);
ui.gridWrap = el('div', {{ className: 'mpc-gridwrap' }}, [table]);
ui.gridZone = el('div', {{ className: 'mpc-gridzone' }}, [ui.gridWrap, ui.expand]);
form.appendChild(ui.gridZone);
form.appendChild(makeGrip(PANES.grid));
setGridColumns(REGISTER_COLUMNS);
renderEmptyGrid('No registers polled yet');
ui.summary = el('div', {{ className: 'mpc-sum', textContent: 'No poll run yet' }});
form.appendChild(el('div', {{ className: 'mpc-check mpc-span9', style: 'justify-content:flex-end' }}, [ui.summary]));
ui.log = el('div', {{ className: 'mpc-log', textContent: 'log line\\n'.repeat(40) }});
form.appendChild(ui.log);
form.appendChild(makeGrip(PANES.log));
panel.appendChild(head);
panel.appendChild(body);
ui.panel = panel;
document.getElementById('host').appendChild(panel);
syncExpandButton();
watchExpanded();

// ---- probes --------------------------------------------------------------
const round = n => Math.round(n);
window.__probe = () => {{
    const b = ui.expand.getBoundingClientRect();
    const g = ui.gridWrap.getBoundingClientRect();
    const th = ui.gridHead.querySelectorAll('th');
    const last = th.length ? th[th.length - 1].getBoundingClientRect() : null;
    return {{
        headHasButton: !!head.querySelector('.mpc-expand'),
        zoneHasButton: !!ui.panel.querySelector('.mpc-gridzone > .mpc-expand'),
        icon: ui.expand.querySelector('path') ? ui.expand.querySelector('path').getAttribute('d') : null,
        title: ui.expand.title,
        rightInline: ui.expand.style.right,
        scrollbar: round(ui.gridWrap.offsetWidth - ui.gridWrap.clientWidth),
        overflowing: ui.gridWrap.scrollHeight > ui.gridWrap.clientHeight,
        // Positive gaps mean the button is inside the table's top-right corner.
        gapFromRight: round(g.right - b.right),
        gapFromTop: round(b.top - g.top),
        pastLastHeading: last ? round(b.left - last.left) >= 0 : null,
        withinHeaderBand: last ? round(b.bottom) <= round(last.bottom) + 2 : null,
        expanded: isExpanded(),
        gridCap: getComputedStyle(ui.gridWrap).maxHeight,
        gridCapInline: ui.gridWrap.style.maxHeight,
        logInline: ui.log.style.height,
        viewport: {{ w: window.innerWidth, h: window.innerHeight }},
        zoneRect: (r => ({{ x: round(r.x), y: round(r.y), w: round(r.width), h: round(r.height) }}))(ui.gridZone.getBoundingClientRect()),
        gridRect: (r => ({{ x: round(r.x), y: round(r.y), w: round(r.width), h: round(r.height) }}))(g),
        panelRect: (r => ({{ x: round(r.x), y: round(r.y), w: round(r.width), h: round(r.height) }}))(ui.panel.getBoundingClientRect()),
        // The console underneath must not have moved: the head is where it was.
        headRect: (r => ({{ x: round(r.x), y: round(r.y), w: round(r.width), h: round(r.height) }}))(head.getBoundingClientRect()),
        logVisible: (r => r.width > 0 && r.bottom > 0 && r.top < window.innerHeight)(ui.log.getBoundingClientRect()),
        stored: {{ ...store }},
    }};
}};
window.__fill = n => {{ fillGrid(n); return window.__probe(); }};
// Drive a grip the way a hand would: press, move in steps, release.
window.__dragGrip = (which, deltaY, steps) => {{
    const grip = document.querySelectorAll('#mpc-panel .mpc-grip')[which === 'grid' ? 0 : 1];
    const r = grip.getBoundingClientRect();
    const x = r.x + r.width / 2;
    const y0 = r.y + r.height / 2;
    const fire = (type, node, y) => node.dispatchEvent(new MouseEvent(type, {{ bubbles: true, clientX: x, clientY: y }}));
    const trail = [];
    fire('mousedown', grip, y0);
    const n = steps || 4;
    for (let i = 1; i <= n; i++) {{
        const y = y0 + (deltaY * i) / n;
        fire('mousemove', window, y);
        const g = grip.getBoundingClientRect();
        const b = ui.body.getBoundingClientRect();
        trail.push({{
            cursorY: Math.round(y),
            gripCentreY: Math.round(g.y + g.height / 2),
            // Negative means the grip has gone below the body's visible edge.
            slackBelow: Math.round(b.bottom - g.bottom),
            bodyScrollTop: Math.round(ui.body.scrollTop),
        }});
    }}
    fire('mouseup', window, y0 + deltaY);
    return {{ trail, probe: window.__probe() }};
}};
// Build a result the way readRegisters would, and render it through the real
// renderGrid. Values are given as [ref, value] pairs.
window.__poll = (pairs, opts) => {{
    const o = opts || {{}};
    const result = {{
        ok: true, plant: '2313', at: new Date().toISOString(),
        spec: {{
            mode: 'tcp', host: '192.168.10.100', port: 502, slave: 1,
            table: o.table || '4', start: pairs[0][0], count: pairs.length,
            base: 'printed', format: o.format || '16-bit',
        }},
        values: pairs.map(([ref, v]) => ({{ i: ref, addr: ref - 1, v }})),
        unreadable: [], notes: [], diagnostics: [], commands: ['modpoll …'],
        summary: {{
            requested: pairs.length, returned: pairs.length,
            nonZero: pairs.filter(p => p[1] !== 0).length,
            min: Math.min(...pairs.map(p => p[1])), max: Math.max(...pairs.map(p => p[1])),
            blocks: 1, elapsedMs: 120,
        }},
    }};
    lastResult = result;
    renderGrid(result);
    return window.__grid();
}};
// Every rendered row as the header labels to cell text, so an assertion reads
// like the grid does.
window.__grid = () => {{
    const heads = [...ui.gridHead.querySelectorAll('th')].map(th => th.textContent);
    const rows = [...ui.gridBody.querySelectorAll('tr')].map(tr => {{
        const cells = [...tr.children];
        if (cells.length !== heads.length) return {{ empty: cells.map(c => c.textContent).join(' ') }};
        const row = {{}};
        heads.forEach((h, i) => {{ row[h] = cells[i].textContent; }});
        row._classes = heads.reduce((acc, h, i) => {{ acc[h] = cells[i].className; return acc; }}, {{}});
        row._titles = heads.reduce((acc, h, i) => {{ acc[h] = cells[i].title; return acc; }}, {{}});
        return row;
    }});
    return {{ heads, rows, summary: ui.summary.textContent }};
}};
window.__toggleZeroFilter = on => {{ ui.filterZero.checked = on; ui.filterZero.dispatchEvent(new Event('change')); return window.__grid(); }};
// A modbusgen list through the real parser, and plant names in the shape
// fetchPlantNames builds — one entry per parameter, several per register when
// they share it bit by bit.
window.__loadList = (json, file) => {{
    pointList = parsePointList(json);
    pointList.file = file || 'test-list.json';
    return {{ points: pointList.points.length, undecodable: pointList.undecodable, subtractOne: pointList.subtractOne }};
}};
window.__setPlantNames = (unitId, entries) => {{
    const byRef = new Map();
    for (const e of entries) {{
        const key = e.table + '||' + e.ref;
        if (!byRef.has(key)) byRef.set(key, []);
        byRef.get(key).push({{
            name: e.name, plantValue: e.plantValue, unit: e.unit || '', bit: e.bit === undefined ? null : e.bit,
            group: e.group || '', access: e.access || 'r',
            driverId: e.driverId || ('2313_VENT_vent_1_1_0_' + ({{ '0': 1, '1': 2, '4': 3, '3': 4 }})[e.table] + '_' + (e.ref - 1) + (e.bit === undefined ? '' : '.' + e.bit)),
            table: e.table, ref: e.ref, protocol: e.ref - 1,
        }});
    }}
    plantNames = {{ unitId, byRef, groups: 1, rows: entries.length, undecodable: 0, at: new Date().toISOString() }};
    return plantNames.byRef.size;
}};
window.__progress = () => ({{
    hidden: ui.progress.classList.contains('mpc-hidden'),
    visible: ui.progress.getBoundingClientRect().height > 0,
    fill: ui.progressFill.style.width,
    fillPx: Math.round(ui.progressFill.getBoundingClientRect().width),
    barPx: Math.round(ui.progressFill.parentElement.getBoundingClientRect().width),
    text: ui.progressText.textContent,
}});
window.__export = () => exportResult(lastResult);
window.__exportText = () => exportText(exportResult(lastResult));
window.__exportParts = base => exportParts(exportResult(lastResult), base);
// Click the n-th data row and read the detail it opens, section by section.
window.__detail = n => {{
    ui.cmd = ui.cmd || {{ value: 'modpoll -1 -m tcp -a 1 -t 4 -r 1 -c 1 192.168.10.100' }};
    const rows = [...ui.gridBody.querySelectorAll('tr:not(.mpc-detail)')];
    rows[n].click();
    const box = ui.gridBody.querySelector('tr.mpc-detail .mpc-detailbox');
    if (!box) return null;
    const out = {{ headline: box.querySelector('.mpc-dhead').textContent, lead: box.querySelector('.mpc-dlead').textContent, sections: {{}} }};
    for (const sec of box.querySelectorAll('.mpc-dsec')) {{
        const title = sec.querySelector('h5').textContent;
        out.sections[title] = {{}};
        for (const kv of sec.querySelectorAll('.mpc-kv')) out.sections[title][kv.querySelector('.mpc-k').textContent] = kv.querySelector('.mpc-v').textContent;
    }}
    return out;
}};
// Drag a grip up from the bottom of a scrolled body: does the grip stay under
// the hand and the pane shrink from its bottom edge, or does the content shift
// and the pane shrink from its top?
window.__dragUpFromBottom = (which, up) => {{
    const spec = which === 'grid' ? PANES.grid : PANES.log;
    const node = ui[spec.node];
    const grip = document.querySelectorAll('#mpc-panel .mpc-grip')[which === 'grid' ? 0 : 1];
    ui.body.scrollTop = ui.body.scrollHeight;
    const r = grip.getBoundingClientRect();
    const x = r.x + r.width / 2;
    const y0 = r.y + r.height / 2;
    const fire = (type, target, clientY) => target.dispatchEvent(new MouseEvent(type, {{ bubbles: true, clientX: x, clientY }}));
    const before = {{ height: paneHeight(spec), top: Math.round(node.getBoundingClientRect().top), bottom: Math.round(node.getBoundingClientRect().bottom) }};
    fire('mousedown', grip, y0);
    const runwayOn = ui.body.style.paddingBottom !== '';
    fire('mousemove', window, y0 - up);
    const g = grip.getBoundingClientRect();
    const n = node.getBoundingClientRect();
    const during = {{ height: paneHeight(spec), top: Math.round(n.top), bottom: Math.round(n.bottom), gripCentreY: Math.round(g.top + g.height / 2), handY: Math.round(y0 - up) }};
    fire('mouseup', window, y0 - up);
    return {{
        before, during,
        shrankBy: before.height - during.height,
        gripUnderHand: Math.abs(during.gripCentreY - during.handY) <= 6,
        bottomEdgeRoseBy: before.bottom - during.bottom,
        topEdgeMovedBy: during.top - before.top,
        runwayOnDuringDrag: runwayOn,
        runwayGoneAfter: ui.body.style.paddingBottom === '',
        heightAfter: paneHeight(spec),
    }};
}};
// Press a grip and hold, the hand where it landed, for a while: does the pane
// keep growing on its own when that is the bottom edge, and stay put when it
// is not? Resolves with the heights before, during and after letting go.
window.__holdGrip = (which, ms, atEdge) => new Promise(resolve => {{
    const spec = which === 'grid' ? PANES.grid : PANES.log;
    const grip = document.querySelectorAll('#mpc-panel .mpc-grip')[which === 'grid' ? 0 : 1];
    const r = grip.getBoundingClientRect();
    const b = ui.body.getBoundingClientRect();
    const y = atEdge === false ? r.y + r.height / 2 : b.bottom - 6;
    const fire = (type, node, clientY) => node.dispatchEvent(new MouseEvent(type, {{ bubbles: true, clientX: r.x + r.width / 2, clientY }}));
    const before = paneHeight(spec);
    fire('mousedown', grip, y);
    setTimeout(() => {{
        const during = paneHeight(spec);
        fire('mouseup', window, y);
        setTimeout(() => resolve({{ before, during, after: paneHeight(spec), grew: during > before, keptAfterRelease: paneHeight(spec) === during, bodyScrollTop: Math.round(ui.body.scrollTop), gripSlack: Math.round(ui.body.getBoundingClientRect().bottom - grip.getBoundingClientRect().bottom) }}), 50);
    }}, ms);
}});
window.__bodyScroll = () => ({{
    scrollTop: Math.round(ui.body.scrollTop),
    scrollHeight: Math.round(ui.body.scrollHeight),
    clientHeight: Math.round(ui.body.clientHeight),
    scrollable: ui.body.scrollHeight > ui.body.clientHeight,
}});
window.__empty = () => {{ renderEmptyGrid('No registers polled yet'); return window.__probe(); }};
</script>
""", encoding="utf-8")
print(f"wrote {OUT} from v{version}")
